# build transporter
FROM golang as builder-transporter
COPY transporter /projects/transporter
WORKDIR /projects/transporter
RUN make build

# build rsync
FROM debian:bullseye as builder-rsync
RUN apt-get update && \
    apt-get install -y make && \
    apt-get install -y gcc g++ gawk autoconf automake && \
    apt-get install -y acl libacl1-dev && \
    apt-get install -y attr libattr1-dev && \
    apt-get install -y libxxhash-dev && \
    apt-get install -y libzstd-dev && \
    apt-get install -y liblz4-dev && \
    apt-get install -y libssl-dev && \
    apt-get install -y libpopt-dev && \
    apt-get install -y zlib1g-dev

COPY rsync /projects/rsync
WORKDIR /projects/rsync
RUN ./configure --disable-md2man && \
    make CFLAGS="-static" EXEEXT="-static"

RUN cp rsync-static rsync
RUN /projects/rsync/rsync --version


# final image
FROM scratch
COPY --from=builder-transporter /projects/transporter/cmd/checksum/checksum /usr/local/bin/
COPY --from=builder-transporter /projects/transporter/cmd/create_wrapper/create-wrapper /usr/local/bin/
COPY --from=builder-transporter /projects/transporter/cmd/mv_wrapper/mv-wrapper /usr/local/bin/
COPY --from=builder-transporter /projects/transporter/cmd/rm_wrapper/rm-wrapper /usr/local/bin/
COPY --from=builder-transporter /projects/transporter/cmd/stat_wrapper/stat-wrapper /usr/local/bin/
COPY --from=builder-transporter /projects/transporter/cmd/copy/copy /usr/local/bin/
COPY --from=builder-transporter /projects/transporter/cmd/copy_cleaner/copy-cleaner /usr/local/bin/
COPY --from=builder-transporter /projects/transporter/cmd/copylist/copylist /usr/local/bin/
COPY --from=builder-rsync /projects/rsync/rsync /usr/local/bin/
