# build transporter
FROM golang as builder-transporter

ENV GOPROXY="https://goproxy.cn"

# build transporter
COPY transporter /projects/transporter
WORKDIR /projects/transporter
RUN make build

# build rsync
FROM centos:centos7 as builder-rsync
RUN yum -y install epel-release && \
    yum -y install gcc gawk autoconf automake make && \
    yum -y install acl libacl-devel && \
    yum -y install attr libattr-devel && \
    yum -y install xxhash-devel && \
    yum -y install libzstd-devel && \
    yum -y install lz4-devel && \
    yum -y install openssl-devel

COPY rsync /projects/rsync
WORKDIR /projects/rsync
RUN ./configure --disable-md2man && \
    make

RUN ldd /projects/rsync/rsync
RUN /projects/rsync/rsync --version


# final image
FROM centos:centos7

COPY --from=builder-transporter /projects/transporter/cmd/checksum/checksum /usr/local/bin/
COPY --from=builder-transporter /projects/transporter/cmd/create_wrapper/create-wrapper /usr/local/bin/
COPY --from=builder-transporter /projects/transporter/cmd/mv_wrapper/mv-wrapper /usr/local/bin/
COPY --from=builder-transporter /projects/transporter/cmd/rm_wrapper/rm-wrapper /usr/local/bin/
COPY --from=builder-transporter /projects/transporter/cmd/stat_wrapper/stat-wrapper /usr/local/bin/
COPY --from=builder-transporter /projects/transporter/cmd/copy/copy /usr/local/bin/
COPY --from=builder-transporter /projects/transporter/cmd/copylist/copylist /usr/local/bin/
COPY --from=builder-rsync /projects/rsync/rsync /usr/local/bin/

RUN yum -y install epel-release && \
    yum -y install libacl acl libattr attr xxhash-libs libzstd lz4 openssl

# clean
RUN yum clean all

# verify
RUN /usr/local/bin/checksum --help
RUN /usr/local/bin/create-wrapper --help
RUN /usr/local/bin/mv-wrapper --help
RUN /usr/local/bin/rm-wrapper --help
RUN /usr/local/bin/stat-wrapper --help
RUN /usr/local/bin/copy --help
RUN /usr/local/bin/copylist --help
RUN ldd /usr/local/bin/rsync
RUN /usr/local/bin/rsync --version
