# build transporter
FROM golang as builder-transporter

COPY transporter /projects/transporter
WORKDIR /projects/transporter
RUN make build


# build rsync
FROM centos:centos7 as builder-rsync
RUN yum -y install epel-release && \
    yum -y install gcc gawk autoconf automake make && \
    yum -y install acl libacl-devel && \
    yum -y install attr libattr-devel && \
    yum -y install xxhash-devel && \
    yum -y install libzstd-devel && \
    yum -y install lz4-devel && \
    yum -y install openssl-devel

COPY rsync /projects/rsync
WORKDIR /projects/rsync
RUN ./configure --disable-md2man && \
    make

RUN ldd /projects/rsync/rsync
RUN /projects/rsync/rsync --version


# final image
FROM centos:centos7

COPY --from=builder-transporter /projects/transporter/cmd/transporter /usr/local/bin/
COPY --from=builder-rsync /projects/rsync/rsync /usr/local/bin/

RUN yum -y install epel-release && \
    yum -y install libacl acl libattr attr xxhash-libs libzstd lz4 openssl

# clean
RUN yum clean all

# verify
RUN /usr/local/bin/transporter --help
RUN ldd /usr/local/bin/rsync
RUN /usr/local/bin/rsync --version
