# build transporter
FROM golang as builder-transporter

ENV GOPROXY="https://goproxy.cn"

# build transporter
COPY transporter /projects/transporter
WORKDIR /projects/transporter
RUN make build

# build rsync
FROM debian:stable-slim as builder-rsync
RUN apt-get update && \
    apt-get install -y make && \
    apt-get install -y gcc g++ gawk autoconf automake && \
    apt-get install -y acl libacl1-dev && \
    apt-get install -y attr libattr1-dev && \
    apt-get install -y libxxhash-dev && \
    apt-get install -y libzstd-dev && \
    apt-get install -y liblz4-dev && \
    apt-get install -y libssl-dev

COPY rsync /projects/rsync
WORKDIR /projects/rsync
RUN ./configure --disable-md2man && \
    make

RUN ldd /projects/rsync/rsync
RUN /projects/rsync/rsync --version


# final image
FROM debian:stable-slim

COPY --from=builder-transporter /projects/transporter/cmd/checksum/checksum /usr/local/bin/
COPY --from=builder-transporter /projects/transporter/cmd/create_wrapper/create-wrapper /usr/local/bin/
COPY --from=builder-transporter /projects/transporter/cmd/mv_wrapper/mv-wrapper /usr/local/bin/
COPY --from=builder-transporter /projects/transporter/cmd/rm_wrapper/rm-wrapper /usr/local/bin/
COPY --from=builder-transporter /projects/transporter/cmd/stat_wrapper/stat-wrapper /usr/local/bin/
COPY --from=builder-transporter /projects/transporter/cmd/copy/copy /usr/local/bin/
COPY --from=builder-transporter /projects/transporter/cmd/copy_cleaner/copy-cleaner /usr/local/bin/
COPY --from=builder-transporter /projects/transporter/cmd/copylist/copylist /usr/local/bin/
COPY --from=builder-rsync /projects/rsync/rsync /usr/local/bin/

RUN apt-get update && \
    apt-get install -y libacl1 acl libattr1 attr libxxhash0 libzstd1 liblz4-1 libssl1.1

# clean
RUN apt-get clean autoclean && \
    apt-get autoremove -y

# verify
RUN /usr/local/bin/checksum --help && \
    /usr/local/bin/create-wrapper --help && \
    /usr/local/bin/mv-wrapper --help && \
    /usr/local/bin/rm-wrapper --help && \
    /usr/local/bin/stat-wrapper --help && \
    /usr/local/bin/copy --help && \
    /usr/local/bin/copy-cleaner --help && \
    /usr/local/bin/copylist --help && \
    ldd /usr/local/bin/rsync && \
    /usr/local/bin/rsync --version
