# build transporter
FROM golang as builder-transporter

COPY transporter /projects/transporter
WORKDIR /projects/transporter
RUN make build


# build rsync
FROM debian:stable-slim as builder-rsync
RUN apt-get update && \
    apt-get install -y make && \
    apt-get install -y gcc g++ gawk autoconf automake && \
    apt-get install -y acl libacl1-dev && \
    apt-get install -y attr libattr1-dev && \
    apt-get install -y libxxhash-dev && \
    apt-get install -y libzstd-dev && \
    apt-get install -y liblz4-dev && \
    apt-get install -y libssl-dev

COPY rsync /projects/rsync
WORKDIR /projects/rsync
RUN ./configure --disable-md2man && \
    make


# final image
FROM debian:stable-slim

COPY --from=builder-transporter /projects/transporter/cmd/transporter /usr/local/bin/
COPY --from=builder-rsync /projects/rsync/rsync /usr/local/bin/

RUN apt-get update && \
    apt-get install -y libacl1 acl libattr1 attr libxxhash0 libzstd1 liblz4-1 libssl1.1

# clean
RUN apt-get clean autoclean && \
    apt-get autoremove -y

# verify
RUN /usr/local/bin/transporter --help
RUN ldd /usr/local/bin/rsync
RUN /usr/local/bin/rsync --version