# build transporter
FROM golang as builder

COPY transporter /projects/transporter
WORKDIR /projects/transporter
RUN make build


# final image
FROM debian:stable-slim

COPY --from=builder /projects/transporter/cmd/transporter /usr/local/bin/

# build rsync
RUN apt-get update && \
    apt-get install -y make && \
    apt-get install -y gcc g++ gawk autoconf automake && \
    apt-get install -y acl libacl1-dev && \
    apt-get install -y attr libattr1-dev && \
    apt-get install -y libxxhash-dev && \
    apt-get install -y libzstd-dev && \
    apt-get install -y liblz4-dev && \
    apt-get install -y libssl-dev

COPY rsync /projects/rsync
WORKDIR /projects/rsync
RUN ./configure --disable-md2man && \
    make

RUN mv rsync /usr/local/bin/
RUN /usr/local/bin/rsync --version

# clean
RUN apt-get clean autoclean && \
    apt-get autoremove -y && \
    rm -rf /projects/*